//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapleLib.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MapleLib.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] CDecrypt {
            get {
                object obj = ResourceManager.GetObject("CDecrypt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edge is a very unstable build, that receives updates often and should be used with caution. Expect errors to shown, bugs to be present, and program crashes.
        ///
        ///Report any errors you come across at http://github.com/Tsume/Maple-Tree..
        /// </summary>
        public static string EdgeBuildNotice {
            get {
                return ResourceManager.GetString("EdgeBuildNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon Green_Light {
            get {
                object obj = ResourceManager.GetObject("Green_Light", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] libeay32 {
            get {
                object obj = ResourceManager.GetObject("libeay32", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] msvcr120d {
            get {
                object obj = ResourceManager.GetObject("msvcr120d", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action will rename all game folders to an organized format.
        ///
        ///See the log window for sample outputs..
        /// </summary>
        public static string OrganizeBtn_Click_ {
            get {
                return ResourceManager.GetString("OrganizeBtn_Click_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Confirm This Action - MapleSeed.
        /// </summary>
        public static string PleaseConfirmAction {
            get {
                return ResourceManager.GetString("PleaseConfirmAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon Red_Light {
            get {
                object obj = ResourceManager.GetObject("Red_Light", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [MapleTree]
        ///; generated by MapleTree
        ///.
        /// </summary>
        public static string Settings_DefaultSettings {
            get {
                return ResourceManager.GetString("Settings_DefaultSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0005000010013000|Nintendo TVii|WUP-X-HBCJ|JAP|No TMD
        ///0005000010100600|鉄拳タッグトーナメント2 Wii U EDITION|WUP-N-AKNJ|00AF|16|JAP|Yes
        ///0005000010100D00|Nintendo×JOYSOUND Wii カラオケ U|WUP-N-WAHJ|112|JAP|Yes
        ///0005000010101800|SiNG PARTY|WUP-N-ASWE|0|USA|Yes
        ///0005000010101900|SiNG PARTY|WUP-P-ASWP|0|EUR|Yes
        ///0005000010101A00|LEGO City: Undercover|WUP-N-APLE|0|USA|Yes
        ///0005000010101B00|LEGO City Undercover|WUP-P-APLP|16|EUR|Yes
        ///0005000010101C00|New スーパーマリオブラザーズ U|WUP-N-ARPJ|16|JAP|Yes
        ///0005000010101D00|New Super Mario Br [rest of string was truncated]&quot;;.
        /// </summary>
        public static string titles {
            get {
                return ResourceManager.GetString("titles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0005000E10100600|TEKKEN TAG TOURNAMENT 2Wii U EDITION|16|JAP
        ///0005000E10110000|TEKKEN TAG TOURNAMENT 2 Wii U EDITION|32|USA
        ///0005000E10101B00|LEGO� CITY UNDERCOVER|16|EUR
        ///0005000E10101C00|New SUPER MARIO BROS. U|32, 48, 65|JAP
        ///0005000E10101D00|New SUPER MARIO BROS. U|32, 48, 64|USA
        ///0005000E10101E00|New SUPER MARIO BROS. U|32, 48, 64, 80|EUR
        ///0005000E10101F00|Nintendo Land|32|JAP
        ///0005000E10102000|Nintendo Land|32|USA
        ///0005000E10102100|Nintendo Land|32|EUR
        ///0005000E10102200|Wii Fit U|32, 48, 64, 81|JAP
        ///0 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string updates {
            get {
                return ResourceManager.GetString("updates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action will delete all contents under the directory {0}.
        /// </summary>
        public static string WillDeleteContents {
            get {
                return ResourceManager.GetString("WillDeleteContents", resourceCulture);
            }
        }
    }
}
